# Critical Claude Task Management Configuration

# Default status for new tasks
default_status: "To Do"

# Available statuses (columns in Kanban board)
statuses:
  - "To Do"
  - "In Progress" 
  - "Done"
  - "Blocked"

# Default assignee for new tasks (optional)
# default_assignee: "@username"

# Automatically commit task changes to git
auto_commit: false

# Date format for timestamps
date_format: "yyyy-mm-dd"

# Default editor for opening tasks
default_editor: "nano"

# Use zero-padded IDs (001, 002, etc.)
zero_padded_ids: false
