# Critical Claude Configuration for Web Applications
# Optimized for modern web apps with user-facing interfaces

[project]
name = "{{PROJECT_NAME}}"
type = "web-app"
language = "{{LANGUAGE}}"
framework = "{{FRAMEWORK}}"
team_size = {{TEAM_SIZE}}
user_count = {{USER_COUNT}}
initialized_at = "{{TIMESTAMP}}"

[requirements]
security_level = "high"
performance_target = "200ms"
concurrent_users = 1000
uptime_sla = 99.9

[critique]
# Web app specific thresholds
[critique.severity_overrides]
xss_severity = "critical"
csrf_severity = "critical"
performance_threshold = "high"
accessibility_threshold = "medium"

[critique.focus_areas]
frontend = ["react-hooks", "state-management", "performance", "accessibility"]
backend = ["api-security", "data-validation", "rate-limiting", "caching"]
infrastructure = ["cdn-usage", "load-balancing", "monitoring", "error-tracking"]

[web_search]
enabled = true
search_depth = "comprehensive"
fact_checking = true
vulnerability_scanning = true

[performance]
# Web-specific performance targets
page_load_target = "3s"
time_to_interactive = "5s"
api_response_target = "200ms"
bundle_size_limit = "500KB"

[security]
# Web app security requirements
require_https = true
require_csp = true
require_cors_config = true
session_timeout = "30m"