# CLI Tool Template
[metadata]
name = "cli-tool"
description = "Command-line interface tool with Node.js"
version = "1.0.0"
difficulty = "beginner"
estimated_weeks = 2
team_size = 1
tags = ["cli", "tool", "node", "terminal"]

[variables]
tool_name = "mycli"
command_prefix = "mc"
package_manager = "npm"
use_typescript = true

[[tasks.default]]
title = "Initialize {{tool_name}} CLI project"
description = "Setup Node.js project with CLI structure and dependencies"
priority = "critical"
labels = ["setup", "cli"]
story_points = 2
estimated_hours = 3

[[tasks.default]]
title = "Implement command parser"
description = "Setup command-line argument parsing with yargs or commander"
priority = "high"
labels = ["cli", "parser"]
story_points = 3
estimated_hours = 5
dependencies = ["1"]

[[tasks.default]]
title = "Create core commands"
description = "Implement main CLI commands and subcommands"
priority = "high"
labels = ["cli", "commands"]
story_points = 5
estimated_hours = 8
dependencies = ["2"]

[[tasks.default]]
title = "Add configuration management"
description = "Implement config files, environment variables, and user preferences"
priority = "medium"
labels = ["config", "cli"]
story_points = 3
estimated_hours = 5
dependencies = ["3"]

[[tasks.default]]
title = "Implement help system"
description = "Create comprehensive help text and usage examples"
priority = "medium"
labels = ["documentation", "cli"]
story_points = 2
estimated_hours = 3
dependencies = ["3"]

[[tasks.default]]
title = "Add interactive prompts"
description = "Implement interactive mode with inquirer for user input"
priority = "low"
labels = ["ux", "cli"]
story_points = 3
estimated_hours = 5
dependencies = ["3"]

[[tasks.default]]
title = "Write unit tests"
description = "Test commands, parsers, and utility functions"
priority = "high"
labels = ["testing", "quality"]
story_points = 5
estimated_hours = 8
dependencies = ["5"]

[[tasks.default]]
title = "Package and publish"
description = "Setup npm publishing, executable generation, and installation docs"
priority = "medium"
labels = ["deployment", "npm"]
story_points = 3
estimated_hours = 5
dependencies = ["7"]