# Mobile Application Template
[metadata]
name = "mobile-app"
description = "Cross-platform mobile application with React Native"
version = "1.0.0"
difficulty = "intermediate"
estimated_weeks = 6
team_size = 3
tags = ["mobile", "react-native", "ios", "android", "app"]

[variables]
app_name = "MyMobileApp"
platform = "react-native"
state_management = "redux"
navigation = "react-navigation"
ui_library = "native-base"

[phases]
foundation = "Foundation & Setup"
features = "Core Features"
release = "Testing & Release"

[tasks]

[[tasks.foundation]]
title = "Setup {{platform}} development environment"
description = "Install dependencies, configure iOS/Android environments"
priority = "critical"
labels = ["setup", "mobile", "environment"]
phase = "foundation"
story_points = 3
estimated_hours = 5

[[tasks.foundation]]
title = "Configure {{navigation}} and app structure"
description = "Setup navigation system, create screen hierarchy"
priority = "high"
labels = ["navigation", "architecture", "mobile"]
phase = "foundation"
story_points = 3
estimated_hours = 5
dependencies = ["foundation-1"]

[[tasks.foundation]]
title = "Implement {{state_management}} store"
description = "Setup global state management, actions, and reducers"
priority = "high"
labels = ["state", "architecture", "mobile"]
phase = "foundation"
story_points = 3
estimated_hours = 5
dependencies = ["foundation-1"]

[[tasks.features]]
title = "Build authentication flow"
description = "Login, registration, and secure token storage"
priority = "critical"
labels = ["auth", "security", "mobile"]
phase = "features"
story_points = 5
estimated_hours = 8
dependencies = ["foundation-2", "foundation-3"]

[[tasks.features]]
title = "Create UI component library with {{ui_library}}"
description = "Build reusable components with consistent styling"
priority = "high"
labels = ["ui", "components", "mobile"]
phase = "features"
story_points = 5
estimated_hours = 8
dependencies = ["foundation-2"]

[[tasks.features]]
title = "Implement core app features"
description = "Build main functionality screens and business logic"
priority = "high"
labels = ["features", "mobile"]
phase = "features"
story_points = 13
estimated_hours = 20
dependencies = ["features-1", "features-2"]

[[tasks.release]]
title = "Add offline support and data persistence"
description = "Implement local storage and sync mechanisms"
priority = "medium"
labels = ["offline", "storage", "mobile"]
phase = "release"
story_points = 5
estimated_hours = 8
dependencies = ["features-3"]

[[tasks.release]]
title = "Write unit and integration tests"
description = "Test components, actions, and user flows"
priority = "high"
labels = ["testing", "quality", "mobile"]
phase = "release"
story_points = 5
estimated_hours = 8
dependencies = ["features-3"]

[[tasks.release]]
title = "Prepare app store releases"
description = "Build production versions, create listings, submit for review"
priority = "high"
labels = ["release", "deployment", "mobile"]
phase = "release"
story_points = 5
estimated_hours = 8
dependencies = ["release-2"]